"use client";

import { useMemo } from "react";

import type { BlockComponents } from "@stream-mdx/react";

import { CopyButton } from "@/components/copy-button";
import { cn } from "@/lib/utils";

type CodeProps = Parameters<BlockComponents["code"]>[0];

function normalizeLanguage(lang: unknown): string {
  if (typeof lang === "string" && lang.trim().length > 0) return lang.trim();
  return "text";
}

function resolveCodeText(meta: Record<string, unknown> | undefined, lines: CodeProps["lines"]): string | null {
  if (meta && typeof meta.code === "string" && meta.code.trim().length > 0) {
    return meta.code;
  }
  if (Array.isArray(lines) && lines.length > 0) {
    return lines.map((line) => line.text).join("\n");
  }
  return null;
}

export function DocsCodeBlock({ html, meta, lines, lang }: CodeProps) {
  const language = normalizeLanguage(lang ?? meta?.lang);
  const copyText = useMemo(() => resolveCodeText(meta, lines), [meta, lines]);
  const languageLabel = language === "text" ? "plain text" : language;

  return (
    <div className={cn("docs-code-block markdown-code-block", `language-${language}`)}>
      <div className="docs-code-block__header">
        <span className="docs-code-block__lang">{languageLabel}</span>
        {copyText ? <CopyButton className="docs-code-block__copy" iconOnly text={copyText} /> : null}
      </div>
      {html ? (
        <div
          className="docs-code-block__body"
          // biome-ignore lint/security/noDangerouslySetInnerHtml: highlighted HTML is generated by our sanitizer
          dangerouslySetInnerHTML={{ __html: html }}
        />
      ) : (
        <div className="docs-code-block__body">
          <pre className="markdown-code-block">
            <code>{copyText ?? ""}</code>
          </pre>
        </div>
      )}
    </div>
  );
}

